# https://hub.docker.com/r/bitnami/mongodb
version: "3"

services:
  mongodb:
    image: bitnami/mongodb
    ports:
      - "27017:27017"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MONGODB_DATABASE=database
