# https://hub.docker.com/r/bitnami/mysql/
version: "3"

services:
  mysql:
    image: bitnami/mysql
    ports:
      - "3306:3306"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=database
