version: "3"

services:
  # https://hub.docker.com/r/bitnami/minio
  minio:
    image: bitnami/minio
    ports:
      - "9000:9000"
    environment:
      - MINIO_ACCESS_KEY=admin
      - MINIO_SECRET_KEY=some_random_password
    volumes:
      - minio-data:/data

volumes:
  minio-data:
