version: "3"

services:
  # https://hub.docker.com/r/bitnami/minio
  minio:
    image: bitnami/minio
    ports:
      - "9000:9000"
    environment:
      - MINIO_ACCESS_KEY=user
      - MINIO_SECRET_KEY=password
