version: "3"

services:
  # https://hub.docker.com/r/bitnami/minio
  minio:
    image: bitnami/minio
    ports:
      - "9000:9000"
    environment:
      - MINIO_ACCESS_KEY=guest
      - MINIO_SECRET_KEY=guest
    volumes:
      - minio-data:/data

volumes:
  minio-data:
