version: "3"

services:
  # https://hub.docker.com/r/bitnami/zookeeper
  zookeeper:
    image: bitnami/zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - zookeeper-data:/bitnami/zookeeper

  # https://hub.docker.com/r/bitnami/zookeeper
  kafka:
    image: bitnami/kafka
    ports:
      - "9092:9092"
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
    volumes:
      - kafka-data:/bitnami/kafka
    depends_on:
      - zookeeper
    restart: on-failure

volumes:
  zookeeper-data:
  kafka-data:
